server:
  port: 9010
  servlet:
    context-path: /bootcamp51/ms/client

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bootcamp51?authSource=admin

sonar:
  host:
    url: "http://XXX.XXX.X.XX:9000"
  login: "XXXX"


rutaApiClient: "http://localhost:9020/bootcamp51/ms/product"
retryApiClient: 3
timeIntervalApiClient: 3
