server:
  port: 9010
  servlet:
    context-path: /bootcamp51/ms/client

spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.51:27017/bootcamp51?authSource=admin


rutaApiClient: "http://localhost:9020/bootcamp51/ms/product"
retryApiClient: 3
timeIntervalApiClient: 3
